In [1]:
import pandas as p
import numpy as n
import matplotlib.pyplot as plt
import seaborn as s
from sklearn.linear_model import LogisticRegression

In [2]:
#read the given dataset
df= p.read_csv("dataset/finaltrain1.csv")

In [3]:
df.drop(columns=df.columns[:1], axis=1,inplace=True)


In [4]:
df.head()

count  diff_srv_rate  dst_bytes  dst_host_count  dst_host_diff_srv_rate  \
0     13           0.15          0             255                    0.60   
1    123           0.07          0             255                    0.05   
2      5           0.00       8153              30                    0.00   
3     30           0.00        420             255                    0.00   
4    121           0.06          0             255                    0.07   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  duration  hot  \
0                         0.88                         0.00         0    0   
1                         0.00                         0.00         0    0   
2                         0.03                         0.04         0    0   
3                         0.00                         0.00         0    0   
4                         0.00                         0.00         0    0   

   last_flag  logged_in  num_compromised  srv_count  srv_diff_host_rate  \
0         15          0                0          1                0.00   
1         19          0                0          6                0.00   
2         21          1                0          5                0.00   
3         21          1                0         32                0.09   
4         21          0                0         19                0.00   

   attack_class  
0             0  
1             1  
2             0  
3             0  
4             1

In [8]:
x = df.iloc[ : , :-1].values
y = df.iloc[:, -1:].values

In [9]:
#spliting the dataset into training set and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.25, random_state =0 )

In [10]:
logreg = LogisticRegression(random_state=0,solver='lbfgs',multi_class='multinomial')
logreg.fit( train_X, train_y)

D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(multi_class='multinomial', random_state=0)

In [12]:
result=logreg.predict(x_test)   #by default, it use cut-off as 0.5

In [13]:
result

array([1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [18]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, result)
print(cm)

[[125   1]
 [ 33  91]]


In [22]:
#pickle file joblib
import joblib
joblib.dump(logreg, 'final_models/lr.pkl')

['final_models/lr.pkl']

In [23]:
list( zip( df.columns, logreg.coef_[0] ) )

[('count', 0.024268846190661927),
 ('diff_srv_rate', 0.018104606977057233),
 ('dst_bytes', -0.00016028668405718288),
 ('dst_host_count', 0.000578902619577801),
 ('dst_host_diff_srv_rate', 0.05466964280899881),
 ('dst_host_same_src_port_rate', 0.23087030725649846),
 ('dst_host_srv_diff_host_rate', 0.08915409472757566),
 ('duration', 4.140899236705682e-05),
 ('hot', 0.26567828943222277),
 ('last_flag', -0.042057263783187464),
 ('logged_in', -0.18528719703685592),
 ('num_compromised', 0.026788326376735144),
 ('srv_count', -0.021869282492262963),
 ('srv_diff_host_rate', 0.09211658998874465)]

In [24]:
logreg.intercept_

array([0.10260858])

In [25]:
logreg.score(train_X,train_y)

0.872